# Generated by Django 5.0.6 on 2024-06-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='is_friends',
            field=models.BooleanField(default=False),
        ),
    ]
